<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaXaml Remove="Themes\Terminal.axaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Themes\Themes.cs" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Themes\Terminal.axaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.1" />
    <PackageReference Include="Avalonia.Headless" Version="12.0.1" />
    <PackageReference Include="Avalonia.Headless.XUnit" Version="12.0.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\Icons.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="TextTemplate1.txt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>TextTemplate1.txt</LastGenOutput>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TextTemplate1.txt</DependentUpon>
    </None>
  </ItemGroup>
</Project>
